# Generated by Django 3.1.2 on 2022-11-04 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_auto_20211130_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buku',
        ),
        migrations.DeleteModel(
            name='Kelompok',
        ),
    ]
